import {getInventory,getCompanion,getHome,getBusiness,getLifeReport} from './engine.js';
import {resourceIcon} from './resource-ui.js';
import {tenDecisionReviewMarkup} from './life-report-view.js';
import {mentorAdviceMarkup,fatigueMarkup} from './rhythm-ui.js';

const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const amount=value=>Number(value||0).toLocaleString('zh-CN');
const shapes={memo:'<path d="M7 4h18v24H7zM11 10h10M11 15h10M11 20h6"/>',earplugs:'<path d="M7 17V12a9 9 0 0 1 18 0v5M5 15h5v10H5zM22 15h5v10h-5z"/>',coffee:'<path d="M7 11h16l-2 17H9zM6 7h18M12 3v2m6-2v2M23 13h4v7h-5"/>',onsen:'<path d="M3 19h26c-1 9-25 9-26 0zM10 15c-7-5 6-5 0-11m7 11c-7-5 6-5 0-11m7 11c-7-5 6-5 0-11"/>',mentor:'<path d="M5 4h22v18l-7 7H5zM20 29v-7h7M10 10h12M10 15h8"/>',legal:'<path d="M5 5c5-2 8-1 11 1 3-2 6-3 11-1v22c-5-2-8-1-11 1-3-2-6-3-11-1zM16 6v22"/>',communication:'<path d="M3 5h21v15H12l-6 5v-5H3zM25 11h4v17l-6-4h-8M8 10h11M8 15h7"/>',oden:'<path d="M6 26 25 5M10 17l6 6M12 13l7 7M18 6l8 8M4 23l5 5"/><circle cx="11" cy="20" r="4"/><path d="m13 13 6-3 3 6-6 3z"/>'};
export function itemIcon(id){return `<svg class="item-icon" viewBox="0 0 32 32" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round" stroke-linecap="round" aria-hidden="true">${shapes[id]||shapes.memo}</svg>`;}
// An original native UI portrait, not a falsely attributed official character asset.
export function companionAvatar(){return '<svg class="companion-avatar" viewBox="0 0 64 64" role="img" aria-label="刘看雨，游戏原创伴侣形象"><rect x="2" y="2" width="60" height="60" rx="18" fill="#ede1d4"/><path d="M16 44V20l9 7h14l9-7v24c0 15-32 15-32 0" fill="#fdfbf1" stroke="#536561" stroke-width="2"/><path d="m39 25 9-7 1 10z" fill="#d49a83"/><circle cx="24" cy="36" r="2" fill="#424c48"/><circle cx="41" cy="36" r="2" fill="#424c48"/><ellipse cx="32" cy="42" rx="5" ry="4" fill="#505d59"/><path d="M22 51h20v5H22z" fill="#d19a82"/></svg>';}
export function lifeBadgeMarkup(state){const c=getCompanion(state);return c?`${companionAvatar()}<span><b>伴侣 · 看雨</b><small>交流与生活计划</small></span><i aria-label="关系 ${c.relationship}">${resourceIcon('heart')}</i>`:'';}
export function inventoryMarkup(state){
  const rows=getInventory(state),life=state.life,buffs=life?.buffs||{};
  const effects=Object.entries({耳塞:buffs.earplugs?`剩 ${buffs.earplugs} 次事件结算`:null,留痕:buffs.memo?'已准备':null,协商清单:buffs.legal?'已准备':null,长期主义:buffs.longTerm?'持续生效':null,韧性练习:buffs.resilience?'持续生效':null}).filter(([,value])=>value);
  return `<div class="life-heading"><span class="tiny-label">旅途行囊</span><h2>带在身边的小办法</h2><p class="inventory-intro">先看效果，再决定何时使用。道具数量与费用会按实际使用扣除。</p></div>${life?`<aside class="inventory-safety"><b>深夜树洞 · ${life.treeholeUsed?'本局已使用':'剩余 1 次守护'}</b><span>事件结算时情绪归零，自动恢复 15 点；每局一次。${life.schema>=2?'有库存的关东煮会优先触发。':''}</span>${life.legacyBonus?`<span>已继承：初始专业 +${life.legacyBonus.exp} · 情绪上限 +${life.legacyBonus.moodMax}</span>`:''}</aside>`:''}${fatigueMarkup(state,{always:true})}${effects.length?`<div class="active-effects">${effects.map(([key,value])=>`<span>${key} · ${value}</span>`).join('')}</div>`:''}<div class="inventory-grid">${rows.map(item=>{
    const guarding=item.id==='oden'&&life?.schema>=2&&item.count>0&&!state.ended;
    return `<article class="inventory-item ${item.count?'':'empty'}">${itemIcon(item.id)}${item.category?`<span class="inventory-category">${esc(item.category)}</span>`:''}<h3>${esc(item.name)}<span>×${item.count}</span></h3>${item.useMode?`<span class="inventory-mode">${esc(item.useMode)}</span>`:''}<p>${esc(item.description)}</p>${item.scene?`<details class="inventory-details"><summary>适用场景与获取方式</summary><dl><dt>适用场景</dt><dd>${esc(item.scene)}</dd><dt>如何获得</dt><dd>${esc(item.acquisition)}</dd><dt>使用限制</dt><dd>${esc(item.limits)}</dd></dl></details>`:''}<button class="secondary" data-use-item="${item.id}" ${item.usable?'':'disabled'}>${item.usable?'手动使用':guarding?'自动守护中':'暂不可用'}</button>${!item.usable?`<small>${guarding?'自动效果已待命；手动使用：':''}${esc(item.disabledReason)}</small>`:''}</article>`;
  }).join('')}</div>${mentorAdviceMarkup(state)}`;
}
export function companionMarkup(state){
  const c=getCompanion(state);if(!c)return '';
  const home=getHome(state),business=getBusiness(state);
  const businessNames={none:'尚未开始',idea:'有了一个想法',tested:'小样已验证',awaiting:'等待试运营交付',operating:'试运营已交付',closed:'已收好这一轮记录'};
  return `<div class="companion-heading">${companionAvatar()}<div><span class="tiny-label">一起过日子</span><h2>伴侣 · 刘看雨</h2><span>${esc(c.status)}</span></div></div><p class="companion-intro">每季可与刘看雨交流一次，增进关系、恢复情绪，或获得事件支持。也可以在下方查看共同的生活计划。</p><p class="companion-relationship-label">本局关系 <strong>${c.relationship} / 100</strong></p><div class="relationship-meter" aria-label="本局关系 ${c.relationship} / 100"><span style="width:${c.relationship}%"></span></div><p class="companion-message">${esc(c.lastMessage)}</p><div class="companion-actions">${[['listen','听你说说','先听完彼此的近况'],['share','聊聊我的今天','交换一段真实经历'],['promise','约好下一次','把支持写进共同约定']].map(([id,label,effect,note])=>`<button class="secondary" data-companion="${id}" ${c.canInteract?'':'disabled'}><b>${label}</b><small>${effect}</small>${note?`<small>${note}</small>`:''}</button>`).join('')}</div>${!c.canInteract?`<small class="muted">${esc(c.disabledReason)}</small>`:''}<p class="companion-effect-note">情绪恢复不超过当前上限。支持次数随每次事件结算消耗，冷战时暂不生效。</p><details class="life-assets"><summary>我们的生活计划</summary><div class="life-plans"><article><h3>一盏属于自己的灯</h3><p>${home.owned?`房贷余款 ¥${amount(home.loan.remaining)} · 已偿还 ¥${amount(home.loan.paid)}`:home.planned?'安家计划已记下。':'还没有安家计划。'}</p>${home.owned?`<small>延期 ${home.loan.deferred} 次</small>`:home.planned?`<p class="muted">游戏首付 ¥60,000；贷款 ¥240,000。每次事件后尝试还款 ¥2,000。</p><button id="purchase-home" class="secondary" ${home.canBuy?'':'disabled'}>确认首付</button>${!home.canBuy?`<small>${esc(home.disabledReason)}</small>`:''}`:''}</article><article><h3>从一个小样开始</h3><p>${businessNames[business.stage]}</p>${business.stage!=='none'?`<div class="business-actions">${business.stage==='idea'?`<button data-business="test" class="secondary" ${business.canTest?'':'disabled'}>验证小样</button>`:''}${business.stage==='tested'?`<button data-business="launch" class="secondary" ${business.canLaunch?'':'disabled'}>确认试运营</button>`:''}${['idea','tested'].includes(business.stage)?`<button data-business="pause" class="text-button" ${business.canPause?'':'disabled'}>先收好记录</button>`:''}</div><details><summary>预算与游戏规则</summary><p>小样预算 ¥2,000，需 5 点情绪；试运营预算 ¥8,000，下一次事件结算 ¥12,000 游戏收入。不是现实收益预测。每回合仅一次支线行动。</p></details>`:''}</article></div></details><details class="life-boundary"><summary>关于这段陪伴</summary><p>刘看雨是本作原创的虚构伴侣形象；关系数值只表示本局相处记录，不评价真实感情。每季可专心交流一次。</p></details>`;
}
export function lifeReportMarkup(state,{compact=false}={}){
  const r=getLifeReport(state);if(!r)return '';
  const unlocked=r.achievements.filter(x=>x.unlocked);
  const keepsakes=(r.commemorations||[]).map(item=>`<details class="life-keepsake"><summary>✦ ${esc(item.name)}</summary><p>${esc(item.reason)}</p></details>`).join('');
  return `<section class="life-report"><span class="tiny-label">这一程的印记</span><h3>${esc(r.title)}</h3><p class="life-title-reason">${esc(r.titleReason||'')}</p>${keepsakes?`<div class="life-keepsakes" aria-label="本局特殊经历纪念">${keepsakes}</div>`:''}<div class="achievement-row">${unlocked.length?unlocked.map(a=>`<span title="${esc(a.description)}">✦ ${esc(a.name)}</span>`).join(''):'<span>新的印记还在路上</span>'}</div>${!compact?tenDecisionReviewMarkup(state):''}<details class="report-fold"><summary>特殊经历与成就图鉴</summary><div class="title-collection">${r.titles.map(t=>`<article class="${t.unlocked?'unlocked':''}"><span>${t.unlocked?'✦':'◇'}</span><h4>${esc(t.name)}</h4><p>${esc(t.description)}</p></article>`).join('')}</div><div class="achievement-collection">${r.achievements.map(a=>`<p class="${a.unlocked?'unlocked':''}"><b>${a.unlocked?'✓':'○'} ${esc(a.name)}</b><small>${esc(a.description)}</small></p>`).join('')}</div></details><details class="report-fold"><summary>行囊、陪伴与生活计划</summary><p>看雨 · ${esc(r.companion.status)} · 本局关系 ${r.companion.relationship}</p><p>${r.assets.home.owned?`安家已确认 · 房贷余款 ¥${amount(r.assets.home.loan.remaining)}`:r.assets.home.planned?'安家仍在规划中':'还未建立安家计划'}</p><p>树洞守护：${r.treehole.used?'本局已使用':'还在身边'}</p></details></section>`;
}
export function lifeLedgerMarkup(state){
  const rows=getLifeReport(state)?.transactions||[];if(!rows.length)return '';
  const signed=n=>`${n>0?'+':''}${amount(n)}`;
  return `<details class="report-fold"><summary>行囊与生活计划的收支 · ${rows.length} 笔</summary><div class="life-ledger">${rows.map(row=>`<article><h4>${esc(row.title)}</h4><small>第 ${row.turn} 次停靠 · 独立行动</small><p>${resourceIcon('coin')} ${signed(row.moneyDelta)}　${resourceIcon('heart')} ${signed(row.moodDelta)}　${resourceIcon('star')} ${signed(row.expDelta)}</p><details><summary>回看这次行动</summary><p>${esc(row.result)}</p></details></article>`).join('')}</div></details>`;
}
